Repository gazebosim/gz-cmake, pull requests merged in 2020-11, with the labels that each got.

#117 Correct CMake Logic and update cpplint to Python3
  cmake/IgnCodeCheck.cmake
  cmake/IgnPython.cmake
  cmake/IgnUtils.cmake
  codecheck/cpplint.py
Labels: 🏢 edifice, 🏰 citadel, 📜 blueprint, 🔮 dome

#125 FindIgnOGRE2: prefer versioned component libraries
  cmake/FindIgnOGRE2.cmake
Labels: macOS, 🏢 edifice, 🏰 citadel, 📜 blueprint, 🔮 dome

#124 Fix FindIgnOgre on Windows when not using vcpkg
  cmake/FindIgnOGRE.cmake
Labels: Windows, 🏢 edifice, 🏰 citadel, 📜 blueprint, 🔮 dome
