Repository gazebosim/gz-cmake, pull requests merged in 2021-12, with the labels that each got.

#194 Add Ubuntu Jammy CI
  .github/workflows/ci.yml
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress, Gazebo 1️1️, 🌱 garden

#195 Prepare for 2.10.0~pre1
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress, Gazebo 1️1️, 🌱 garden

#196 Add HIDE_SYMBOLS_BY_DEFAULT option
  cmake/IgnConfigureBuild.cmake
  cmake/IgnSetCompilerFlags.cmake
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress, Gazebo 1️1️, 🌱 garden

#197 Prepare for 2.10.0~pre2
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress, Gazebo 1️1️, 🌱 garden

#199 Add LEGACY_PROJECT_PREFIX option
  cmake/IgnPackaging.cmake
  cmake/IgnUtils.cmake
  cmake/ignition-config.cmake.in
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress, Gazebo 1️1️, 🌱 garden

#200 Prepare for 2.10.0~pre3 release
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress, Gazebo 1️1️, 🌱 garden

#198 Doxygen allow all .cc .hh and CMakeLists.txt files
  doc/doxygen/api.in
Labels: documentation, 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress, Gazebo 1️1️, 🌱 garden

#201 Prepare for 2.10.0 stable release
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel, 🏢 edifice, 🏯 fortress, Gazebo 1️1️, 🌱 garden
