Repository gazebosim/gz-cmake, pull requests merged in 2021-03, with the labels that each got.

#160 Master branch updates
  .github/workflows/ci.yml
  README.md
  tools/doc_check.sh
  tutorials/developing_with_ign-cmake.md
  tutorials/install.md
Labels: 🏢 edifice, 🏰 citadel, 📜 blueprint, 🔮 dome

#154 glib fix for Windows
  cmake/FindGTS.cmake
Labels: Windows, bug, 🏢 edifice, 🏰 citadel, 📜 blueprint, 🔮 dome

#157 Find Ogre 2-2
  cmake/FindIgnOGRE2.cmake
  examples/find_ogre2/README.md
  examples/find_ogre2/ogre-2.1/CMakeLists.txt
  examples/find_ogre2/ogre-2.2/CMakeLists.txt
Labels: beta, 🏢 edifice, 🏰 citadel, 📜 blueprint, 🔮 dome

#161 🎈 2.7.0~pre2
  CMakeLists.txt
  Changelog.md
Labels: beta, 🏢 edifice, 🏰 citadel, 📜 blueprint, 🔮 dome

#162 🎈 2.7.0
  CMakeLists.txt
  Changelog.md
Labels: 🏢 edifice, 🏰 citadel, 📜 blueprint, 🔮 dome
