Repository gazebosim/gz-cmake, pull requests merged in 2022-07, with the labels that each got.

#272 Exclude proto generated files in coverage test
  cmake/IgnCodeCoverage.cmake
Labels: 🏰 citadel, 🏯 fortress, Gazebo 1️1️, QA

#273 ign -> gz FindXXX migration : gz-cmake
  Changelog.md
  cmake/FindGzBullet.cmake
  cmake/FindGzCURL.cmake
  cmake/FindGzOGRE.cmake
  cmake/FindGzOGRE2.cmake
  cmake/FindGzProtobuf.cmake
  cmake/FindGzURDFDOM.cmake
  cmake/IgnImportTarget.cmake
  cmake/IgnRonn2Man.cmake
  cmake/IgnUtils.cmake
  examples/find_ogre2/README.md
Labels: 🌱 garden

#277 ign -> gz Migrate Internal CMake Vars : gz-cmake
  .github/workflows/ci.yml
  .github/workflows/pr-collection-labeler.yml
  CMakeLists.txt
  Changelog.md
  Migration.md
  MigrationFromClassic.md
  README.md
  api.md.in
  benchmark/run_benchmarks.py
  cmake/FindGzProtobuf.cmake
  cmake/GzBenchmark.cmake
  cmake/GzCMake.cmake
  cmake/GzCheckSSE.cmake
  cmake/GzCodeCheck.cmake
  cmake/GzCodeCoverage.cmake
  cmake/GzConfigureBuild.cmake
  cmake/GzConfigureProject.cmake
  cmake/GzCreateDocs.cmake
  cmake/GzGenerateVersionInfo.cmake
  cmake/GzPackaging.cmake
  cmake/GzPython.cmake
  cmake/GzRonn2Man.cmake
  cmake/GzSanitizers.cmake
  cmake/GzSetCompilerFlags.cmake
  cmake/GzUtils.cmake
  cmake/cpack_options.cmake.in
  cmake/gz-component-config.cmake.in
  cmake/gz-config.cmake.in
  cmake/gz_auto_headers.hh.in
  cmake/pkgconfig/gz-component.pc.in
  cmake/pkgconfig/gz.pc.in
  cmake/upload_doc.sh.in
  cmake/version_info.json.in
  codecheck/cpplint.py
  config/gz-cmake-config.cmake.in
  config/gz-cmake.pc.in
  doc/CMakeLists.txt
  doc/doxygen/api.in
  doc/doxygen/header.html
  examples/CMakeLists.txt
  examples/comp_deps/CMakeLists.txt
  examples/comp_deps/child/CMakeLists.txt
  examples/comp_deps/parent/CMakeLists.txt
  examples/core_nodep/CMakeLists.txt
  examples/core_nodep_static/CMakeLists.txt
  examples/find_ogre2/ogre-2.1/CMakeLists.txt
  examples/no_gz_prefix/CMakeLists.txt
  examples/no_gz_prefix/README.md
  tools/doc_check.sh
  tutorials.md.in
  tutorials/developing_with_gz-cmake.md
  tutorials/gz_cmake_sanitizers.md
  tutorials/install.md
Labels: 🌱 garden, ign to gz

#280 Merge ign-cmake2 ➡️ main
  .github/CODEOWNERS
  cmake/GzCodeCoverage.cmake
  cmake/GzSetCompilerFlags.cmake
Labels: 🌱 garden

#281 Upload docs to an s3 bucket based only on the major version
  cmake/ignition-config.cmake.in
  cmake/upload_doc.sh.in
Labels: documentation, 🏰 citadel, 🏯 fortress, Gazebo 1️1️

#284 Backport GZ_DESIGNATION tick-tock
  api.md.in
  cmake/IgnConfigureProject.cmake
  cmake/IgnCreateDocs.cmake
  cmake/IgnPackaging.cmake
  cmake/IgnUtils.cmake
  cmake/cpack_options.cmake.in
  cmake/ignition-config.cmake.in
  cmake/pkgconfig/ignition-component.pc.in
  cmake/pkgconfig/ignition.pc.in
  cmake/upload_doc.sh.in
  config/ignition-cmake.pc.in
  doc/doxygen/api.in
  tutorials.md.in
Labels: 🏰 citadel, 🏯 fortress, Gazebo 1️1️, ign to gz

#285 Prepare for 2.13.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel, 🏯 fortress, Gazebo 1️1️

#279 Add code coverage ignore file
  cmake/IgnCodeCoverage.cmake
Labels: enhancement, 🏰 citadel, 🏯 fortress, Gazebo 1️1️, QA

#283 Changes for OGRE-2.3
  cmake/FindGzOGRE2.cmake
  examples/find_ogre2/ogre-2.3/CMakeLists.txt
Labels: enhancement, 🌱 garden

#278 CMake macro to find the assimp library
  cmake/FindGzAssimp.cmake
Labels: enhancement, 🌱 garden

#276 Update doxygen file
  doc/doxygen/api.in
Labels: documentation, 🏰 citadel, 🏯 fortress, Gazebo 1️1️

#289 Merge ign-cmake2 ➡️ main
  Changelog.md
  cmake/GzCodeCoverage.cmake
  cmake/gz-config.cmake.in
  cmake/upload_doc.sh.in
  doc/doxygen/api.in
Labels: 🌱 garden

#291 Change FindGzAssimp to use find_package
  cmake/FindGzAssimp.cmake
Labels: bug, 🌱 garden

#292 Override CMP0012 policy for Assimp
  cmake/FindGzAssimp.cmake
Labels: 🌱 garden
