Repository gazebosim/gz-cmake, pull requests merged in 2022-04, with the labels that each got.

#210 Specify sanitizers using IGN_SANITIZERS cmake variable
  README.md
  cmake/IgnCMake.cmake
  cmake/IgnSanitizers.cmake
  examples/CMakeLists.txt
  examples/sanitizers/CMakeLists.txt
  examples/sanitizers/src/CMakeLists.txt
  examples/sanitizers/src/asan_fail.cc
  tutorials.md.in
  tutorials/developing_with_ign-cmake.md
  tutorials/ign_cmake_sanitizers.md
Labels: 🏰 citadel, 🏢 edifice, 🏯 fortress, Gazebo 1️1️, 🌱 garden

#219 FindIgnOGRE2: exclude ogre versions different than 2.x
  cmake/FindIgnOGRE2.cmake
Labels: 🏰 citadel, 🏢 edifice, 🏯 fortress, Gazebo 1️1️, 🌱 garden

#220 Fix UNIX check for missing components in OGRE2. Be more verbose with components
  cmake/FindIgnOGRE2.cmake
Labels: 🏰 citadel, 🏯 fortress, Gazebo 1️1️, 🌱 garden

#223 IgnPython: restore PYTHON_EXECUTABLE for now
  cmake/IgnPython.cmake
Labels: 🏰 citadel, 🏯 fortress, Gazebo 1️1️, 🌱 garden

#211 Adding CONFIG option
  cmake/IgnUtils.cmake
Labels: 🏰 citadel, 🏢 edifice, 🏯 fortress, Gazebo 1️1️, 🌱 garden

#224 IgnFindOGRE2: support for the ogre-next package on Ubuntu Jammy
  cmake/FindIgnOGRE2.cmake
Labels: 🏰 citadel, 🏯 fortress, Gazebo 1️1️, 🌱 garden

#230 Adding tests for CONFIG argument
  examples/CMakeLists.txt
  examples/use_config_ifp/CMakeLists.txt
  examples/use_config_ifp/Findignition-find_config.cmake
  examples/use_config_ifp/README.md
  examples/use_config_ifp/ignition-find_configConfig.cmake
  examples/use_config_ifp/src/CMakeLists.txt
Labels: 🏰 citadel, 🏯 fortress, Gazebo 1️1️, 🌱 garden

#233 Deprecate utilities in favor of ign-utils
  CMakeLists.txt
  MIGRATION.md
  Migration.md
  include/ignition/utilities/ExtraTestMacros.hh
  include/ignition/utilities/SuppressWarning.hh
  test/CMakeLists.txt
  test/warning/CMakeLists.txt
  test/warning/nonvirtual_destructor.cc
Labels: 🌱 garden

#235 Improving CONFIG test
  examples/use_config_ifp/CMakeLists.txt
  examples/use_config_ifp/Findignition-find_config.cmake
  examples/use_config_ifp/ignition-find_configConfig.cmake
Labels: 🏰 citadel, 🏯 fortress, Gazebo 1️1️

#236 2 ➡️ 3 (main)
  Changelog.md
  cmake/FindIgnOGRE2.cmake
  cmake/IgnPkgConfig.cmake
  cmake/IgnUtils.cmake
  examples/CMakeLists.txt
  examples/use_config_ifp/CMakeLists.txt
  examples/use_config_ifp/Findignition-find_config.cmake
  examples/use_config_ifp/README.md
  examples/use_config_ifp/ignition-find_configConfig.cmake
  examples/use_config_ifp/src/CMakeLists.txt
Labels: 🌱 garden

#237 Remove adlarkin as ign-cmake codeowner
  .github/CODEOWNERS
Labels: 🏰 citadel, 🏯 fortress, Gazebo 1️1️

#238 2 to 3
  .github/CODEOWNERS
Labels: 🌱 garden

#242 Rename MIGRATION file
  MigrationFromClassic.md
Labels: 🌱 garden
