Repository gazebosim/gz-cmake, pull requests merged in 2023-08, with the labels that each got.

#371 Fix Github project automation for new project board
  .github/workflows/triage.yml
Labels: 🌱 garden, 🎵 harmonic

#372 Use `pull_request_target` for triage workflow
  .github/workflows/triage.yml
Labels: 🌱 garden, 🎵 harmonic

#374 Fix pkg_config_entry when version number is not specified
  cmake/GzPkgConfig.cmake
Labels: 🌱 garden, 🎵 harmonic

#375 Prepare for 3.3.1 Release
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden, 🎵 harmonic

#376 FindIgnOgre*: fix LIBRARY_DIRS and PLUGINDIR resolution when using pkgconfig
  cmake/FindIgnOGRE.cmake
  cmake/FindIgnOGRE2.cmake
Labels: 🏰 citadel, 🏯 fortress

#379 Merge ign-cmake2 ➡️ gz-cmake3
  cmake/FindGzOGRE.cmake
  cmake/FindGzOGRE2.cmake
Labels: 🌱 garden, 🎵 harmonic

#380 Only link against DL in the case that it is needed
  cmake/GzRelocatableBinaries.cmake
Labels: beta, 🌱 garden, 🎵 harmonic

#382 Move DL fatal message
  cmake/GzRelocatableBinaries.cmake
Labels: 🌱 garden, 🎵 harmonic

#381 Prepare for 3.4.0 Release
  CMakeLists.txt
  Changelog.md
Labels: beta, 🌱 garden, 🎵 harmonic

#383 Prepare for 2.17.1 Release
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel, beta, 🏯 fortress
