Repository gazebosim/gz-cmake, pull requests merged in 2024-07, with the labels that each got.

#433 Fix link for Sanitizer Builds tutorial
  tutorials/gz_cmake_sanitizers.md
Labels: 🌱 garden, 🎵 harmonic

#435 Accept arbitrary capitalization for coverage build type
  cmake/GzCodeCoverage.cmake
Labels: 🏛️ ionic

#434 Deprecate BUILD_DOCS: generate always the doc target but exclude from default make
  Migration.md
  cmake/GzCreateDocs.cmake
Labels: 🏛️ ionic

#436 Fix lcov on Ubuntu Noble
  cmake/GzCodeCoverage.cmake
Labels: beta, 🏛️ ionic

#441 Revert "Fix lcov on Ubuntu Noble (#436)"
  cmake/GzCodeCoverage.cmake
Labels: 🏛️ ionic
