Repository gazebosim/gz-cmake, pull requests merged in 2024-03, with the labels that each got.

#414 Remove @mxgrey as codeowner and assign maintainership to @scpeters
  .github/CODEOWNERS
  README.md
Labels: 🌱 garden

#415 Merge ign-cmake2 ➡️ gz-cmake3
  .github/CODEOWNERS
  README.md
Labels: 🌱 garden, 🎵 harmonic

#416 Prepare for 3.5.0 Release
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden, 🎵 harmonic

#418 Use default flags for RelWithDebInfo
  cmake/GzSetCompilerFlags.cmake
Labels: 🏛️ ionic

#419 Fix how `ign` compatibility files are copied in windows
  CMakeLists.txt
Labels: 🌱 garden, 🎵 harmonic

#420 Prepare for 3.5.1 Release
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden, 🎵 harmonic
