Repository gazebosim/gz-cmake, pull requests merged in 2024-05, with the labels that each got.

#424 Enable 24.04 CI
  .github/workflows/ci.yml
Labels: 🏛️ ionic

#425 Fix installation of `Ign*.cmake` modules on newer versions of CMake
  CMakeLists.txt
Labels: 🌱 garden, 🎵 harmonic

#426 Prepare for 3.5.3 Release
  CMakeLists.txt
  Changelog.md
  package.xml
Labels: 🌱 garden, 🎵 harmonic

#427 Backport #402: Replace `exec_program` with `execute_process`
  cmake/IgnCheckSSE.cmake
  cmake/IgnSetCompilerFlags.cmake
  cmake/cmake_uninstall.cmake.in
Labels: 🏰 citadel, 🏯 fortress

#428 Merge gz-cmake3 ➡️ main
  .github/CODEOWNERS
  .github/workflows/package_xml.yml
  CMakeLists.txt
  Changelog.md
  README.md
  cmake/GzCodeCheck.cmake
  cmake/GzConfigureProject.cmake
  cmake/upload_doc.sh.in
  codecheck/cpplint.py
  examples/CMakeLists.txt
  package.xml
  tools/check_test_ran.py
Labels: 🏛️ ionic

#430 Prepare for release 2.17.2
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden, 🎵 harmonic
